//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriMar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriMar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo do alimento (1 - 2 - 3):.
        /// </summary>
        internal static string AlimentoGrupo {
            get {
                return ResourceManager.GetString("AlimentoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimento: .
        /// </summary>
        internal static string AlimentoNome {
            get {
                return ResourceManager.GetString("AlimentoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor calórico: .
        /// </summary>
        internal static string AlimentoValorCalorico {
            get {
                return ResourceManager.GetString("AlimentoValorCalorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================================================================.
        /// </summary>
        internal static string BarraDietaExibirCombinacoes {
            get {
                return ResourceManager.GetString("BarraDietaExibirCombinacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------.
        /// </summary>
        internal static string BarraDivisaoEntreObjetos {
            get {
                return ResourceManager.GetString("BarraDivisaoEntreObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================================.
        /// </summary>
        internal static string BarraMenus {
            get {
                return ResourceManager.GetString("BarraMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento:.
        /// </summary>
        internal static string ClienteDataNascimento {
            get {
                return ResourceManager.GetString("ClienteDataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string ClienteEmail {
            get {
                return ResourceManager.GetString("ClienteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço:.
        /// </summary>
        internal static string ClienteEndereco {
            get {
                return ResourceManager.GetString("ClienteEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente:.
        /// </summary>
        internal static string ClienteNome {
            get {
                return ResourceManager.GetString("ClienteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone:.
        /// </summary>
        internal static string ClienteTelefone {
            get {
                return ResourceManager.GetString("ClienteTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefones.
        /// </summary>
        internal static string ClienteTelefones {
            get {
                return ResourceManager.GetString("ClienteTelefones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string ConsultaData {
            get {
                return ResourceManager.GetString("ConsultaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário:.
        /// </summary>
        internal static string ConsultaHorario {
            get {
                return ResourceManager.GetString("ConsultaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Cliente:.
        /// </summary>
        internal static string ConsultaNomeCliente {
            get {
                return ResourceManager.GetString("ConsultaNomeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe cliente com o código informado.
        /// </summary>
        internal static string ConsultaPacienteNEncontrado {
            get {
                return ResourceManager.GetString("ConsultaPacienteNEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % de gordura corporal:.
        /// </summary>
        internal static string ConsultaPercentGordura {
            get {
                return ResourceManager.GetString("ConsultaPercentGordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso:.
        /// </summary>
        internal static string ConsultaPeso {
            get {
                return ResourceManager.GetString("ConsultaPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições alimentares:.
        /// </summary>
        internal static string ConsultaRestricoes {
            get {
                return ResourceManager.GetString("ConsultaRestricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensação Física:.
        /// </summary>
        internal static string ConsultaSensacaoFisica {
            get {
                return ResourceManager.GetString("ConsultaSensacaoFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string MenuAdicionar {
            get {
                return ResourceManager.GetString("MenuAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        internal static string MenuClientesListar {
            get {
                return ResourceManager.GetString("MenuClientesListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de consultas:.
        /// </summary>
        internal static string MenuConsultasLista {
            get {
                return ResourceManager.GetString("MenuConsultasLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar por paciente.
        /// </summary>
        internal static string MenuConsultasListarPorPaciente {
            get {
                return ResourceManager.GetString("MenuConsultasListarPorPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar todas.
        /// </summary>
        internal static string MenuConsultasListarTodas {
            get {
                return ResourceManager.GetString("MenuConsultasListarTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string MenuPrincipalOpcaoClientes {
            get {
                return ResourceManager.GetString("MenuPrincipalOpcaoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        internal static string MenuPrincipalOpcaoConsultas {
            get {
                return ResourceManager.GetString("MenuPrincipalOpcaoConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar dieta.
        /// </summary>
        internal static string MenuPrincipalOpcaoDieta {
            get {
                return ResourceManager.GetString("MenuPrincipalOpcaoDieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string MenuPrincipalOpcaoSair {
            get {
                return ResourceManager.GetString("MenuPrincipalOpcaoSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string MenuVoltar {
            get {
                return ResourceManager.GetString("MenuVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja adicionar outro telefone ([s] - sim / [qualquer tecla] - não)?.
        /// </summary>
        internal static string MsgClientesAdicionarNovoTel {
            get {
                return ResourceManager.GetString("MsgClientesAdicionarNovoTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não possui nenhum cliente cadastrado..
        /// </summary>
        internal static string MsgClientesNenhumCliente {
            get {
                return ResourceManager.GetString("MsgClientesNenhumCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha as informações do cliente:.
        /// </summary>
        internal static string MsgClientesPreencherInform {
            get {
                return ResourceManager.GetString("MsgClientesPreencherInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para adicionar uma consulta é necessário que exista ao menos um cliente cadastrado..
        /// </summary>
        internal static string MsgConsultasCadastroPaciente {
            get {
                return ResourceManager.GetString("MsgConsultasCadastroPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o código do paciente:.
        /// </summary>
        internal static string MsgConsultasInformPaciente {
            get {
                return ResourceManager.GetString("MsgConsultasInformPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você ainda não possui nenhuma consulta cadastrada..
        /// </summary>
        internal static string MsgConsultasNExiste {
            get {
                return ResourceManager.GetString("MsgConsultasNExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente não existe ou não existem consultas cadastradas para ele..
        /// </summary>
        internal static string MsgConsultasPacienteNExisteConsulta {
            get {
                return ResourceManager.GetString("MsgConsultasPacienteNExisteConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Preencha as informações da consulta: &quot;.
        /// </summary>
        internal static string MsgConsultasPreenchaInform {
            get {
                return ResourceManager.GetString("MsgConsultasPreenchaInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinações possíveis para um consumo calórico de [&quot;  {0}  &quot;]:.
        /// </summary>
        internal static string MsgDietaCombinacoesPossiveis {
            get {
                return ResourceManager.GetString("MsgDietaCombinacoesPossiveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a meta de consumo calórico para o cliente:.
        /// </summary>
        internal static string MsgDietaInformeMeta {
            get {
                return ResourceManager.GetString("MsgDietaInformeMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma nova meta de consumo calórico para o cliente:.
        /// </summary>
        internal static string MsgDietaInformeNovaMeta {
            get {
                return ResourceManager.GetString("MsgDietaInformeNovaMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar pelo menos um alimento de cada grupo. Continuar? ([s] - sim / [qualquer tecla] - não)?.
        /// </summary>
        internal static string MsgDietaNaoContemTodosGrupos {
            get {
                return ResourceManager.GetString("MsgDietaNaoContemTodosGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja adicionar outro alimento ([s] - sim / [qualquer tecla] - não)?.
        /// </summary>
        internal static string MsgDietaNovoAlimento {
            get {
                return ResourceManager.GetString("MsgDietaNovoAlimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja informar uma nova meta de calorias para os mesmos alimentos ([s] - sim / [qualquer tecla] - não)?.
        /// </summary>
        internal static string MsgDietaPerguntaNovaMeta {
            get {
                return ResourceManager.GetString("MsgDietaPerguntaNovaMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha as informações necessárias: .
        /// </summary>
        internal static string MsgDietaPreencherInfo {
            get {
                return ResourceManager.GetString("MsgDietaPreencherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma combinação encontrada..
        /// </summary>
        internal static string MsgDietaSemCombinacoes {
            get {
                return ResourceManager.GetString("MsgDietaSemCombinacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma opção: .
        /// </summary>
        internal static string MsgMenuSelecionarOpcao {
            get {
                return ResourceManager.GetString("MsgMenuSelecionarOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para retornar a lista de opções..
        /// </summary>
        internal static string MsgPressioneTeclaPVoltar {
            get {
                return ResourceManager.GetString("MsgPressioneTeclaPVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para sair..
        /// </summary>
        internal static string MsgPressioneTelcaParaSair {
            get {
                return ResourceManager.GetString("MsgPressioneTelcaParaSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de clientes:.
        /// </summary>
        internal static string TituloClientesListagem {
            get {
                return ResourceManager.GetString("TituloClientesListagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Dieta.
        /// </summary>
        internal static string TituloMenuDieta {
            get {
                return ResourceManager.GetString("TituloMenuDieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu NutriMar.
        /// </summary>
        internal static string TituloMenuPrincipal {
            get {
                return ResourceManager.GetString("TituloMenuPrincipal", resourceCulture);
            }
        }
    }
}
